Removes ability for RTP's to override requirements
ComputerScienceHouse/Constitution pull request #224
Opened 2022-08-27 02:10 UTC by SpencerCreveling

Check one:
- [x] Semantic Change: something about the meaning of the text is different
- [ ] Non-semantic Change: Spelling, grammar, or formatting changes.

Summary of change(s):
removing the ability for RTP's to override the requirements outlined in the constitution to elect a new RTP. Would require a constitutional override instead if an ineligible RTP was to be elected.

2022-08-27 02:14 UTC, geoffmoss0 commented
Wasn’t this going to be in conjunction with removing requirements for Opcomm? Should those two changes be part of the same amendment?

2022-08-27 02:17 UTC, SpencerCreveling commented
I'm not really sure what your referring to Geo, but usually I don't like grouping amendments together because some members might want to pass one part of the amendment and not the other.

2022-08-27 03:05 UTC, mcsaucy commented
What problem does this PR solve?

Also would this apply retroactively?

Folks who fall out of good standing (or graduate) would fail the meet the requirements of RTP candidacy, which probably isn't ideal given 1) de-RTPing requires a toil-heavy credential rotation; 2) retaining volunteer sysadmins has historically been hard enough as is; and 3) y'all have way more systems to maintain than you did a year ago which suggests the need for more bodies, not fewer. 

Seems like there's value in making it easier to give folks root so they can help out, so why add process?

2022-10-31 19:19 UTC, galenguyer requested changes

2022-10-31 19:19 UTC, galenguyer commented on constitution.tex
>  	\item Candidates must have been an On-Floor Active Member in good standing within the last twelve months, or been an Off-Floor Active Member and have lived on the floor within the last twelve months
Spencer and I talked a few weeks ago and agreed that removing the RTP's ability to waive requirements would be reasonable if we adjusted the requirements to also be more reasonable. I suggested and we agreed upon the following change:
```suggestion
	\item Candidates must have been an Active Member within the last twelve months.
```

2024-05-01 15:04 UTC, esoccoli commented
Resolved by #232

2024-05-01 15:04 UTC, closed without merging